version: '3.4'

x-logging:
  &default-logging
  driver: journald


services:
  spr-mitmproxy:
    container_name: spr-mitmproxy
    image: ghcr.io/spr-networks/spr-mitmproxy:${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}
    build:
      context: "${BUILDCTX:-.}"
    logging: *default-logging
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.route_localnet=1
    networks:
      mitmnet:
    volumes:
      - "${SUPERDIR}./state/plugins/spr-mitmproxy:/state/plugins/spr-mitmproxy"
      - "${SUPERDIR}./configs/plugins/spr-mitmproxy:/configs/spr-mitmproxy"

networks:
  mitmnet:
    driver_opts:
      com.docker.network.bridge.name: mitmweb0
