version: '3.4'

x-logging:
  &default-logging
  driver: journald


services:
  mitmproxy_plugin:
    container_name: mitmproxy-plugin
    build:
      context: .
    logging: *default-logging
    privileged: true
    network_mode: mitmnet

networks:
  mitmnet:
    driver_opts:
      com.docker.network.bridge.name: site99
