version: '3.4'

x-logging:
  &default-logging
  driver: journald


services:
  mitmproxy_plugin:
    container_name: mitmproxy-plugin
    build:
      context: .
    logging: *default-logging
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.route_localnet=1
    networks:
      mitmnet:

networks:
  mitmnet:
    driver_opts:
      com.docker.network.bridge.name: mitmproxy0
